version: 2.1

jobs:
  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["5f:7b:d4:d7:d8:88:61:0b:21:eb:b9:cc:cd:ed:53:c1"] # You can get this ID in the section where you registered the SSH Key
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      # - run:
      #     name: add ssh knwon hosts
      #     command: |
      #       echo "ec2-18-219-246-246.us-east-2.compute.amazonaws.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBzoe0wBAMTCsLMfj5f3LyASaHC+YoQJc8qzXc0qMC1v" > ~/.ssh/known_hosts
      - run:
          name: Configure server
          environment:
            ANSIBLE_HOST_KEY_CHECKING: False
          command: |
            echo yes |
            ansible-playbook -i inventory.txt playbook.yml

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
